name: Deploy
inputs:
  githubToken:
    description: 'github token'
    required: true
  project:
    description: 'project to deploy'
    required: true
  version:
    description: 'Docker image version to deploy'
    required: true
  env:
    description: 'APP_ENV to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to ${{ inputs.env }}
      run: echo "Simulating Deployment ${{ inputs.project }} ${{ inputs.version }} ${{ inputs.env }}"
      shell: bash     
        
    - name: Comment on Issue      
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.deployIssue.outputs.number }}
        body: 'Deployment to ${{ inputs.env }} completed 🌟'

    - name: Update deploy issue with env labels
      uses: KeisukeYamashita/attach-labels@v1
      with:
        token: ${{ inputs.githubToken }}
        number: ${{ steps.deployIssue.outputs.number }}
        labels: ${{ inputs.env }}
