name: Deploy
inputs:
  githubToken:
    description: 'github token'
    required: true
  projects:
    description: 'projects to deploy'
    required: true
  version:
    description: 'Docker image version to deploy'
    required: true
  env:
    description: 'APP_ENV to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to ${{ inputs.env }}
      run: echo "Simulating Deployment ${{ inputs.projects }} ${{ inputs.version }} ${{ inputs.env }}
      shell: bash     
        
    - name: Update deploy issue with env labels
      uses: KeisukeYamashita/attach-labels@v1
      with:
        token: ${{ inputs.githubToken }}
        number: ${{ steps.deployIssue.outputs.number }}
        labels: ${{ inputs.env }}
