name: Deploy
inputs:
  githubToken:
    description: 'github token'
    required: true
  issueNumber:
    description: 'Issue number to update'
    required: true
  project:
    description: 'project to deploy'
    required: true
  version:
    description: 'Docker image version to deploy'
    required: true
  environment:
    description: 'APP_ENV to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to ${{ inputs.environment }}
      run: echo "Simulating Deployment ${{ inputs.project }} ${{ inputs.version }} ${{ inputs.environment }}"
      shell: bash     
        
    - name: Comment on Issue      
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ inputs.issueNumber }}
        body: 'Deployment to ${{ inputs.environment }} completed 🌟'

    - name: Update deploy issue with environment labels
      uses: KeisukeYamashita/attach-labels@v1
      with:
        token: ${{ inputs.githubToken }}
        number: ${{ inputs.issueNumber }}
        labels: ${{ inputs.environment }}
