name: CI

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'projects to deploy'
        required: true
      version:
        description: 'version to deploy'
        required: true

jobs:  
  create:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(inputs.projects)}}
    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'hello youtube' > output.txt

      - name: Create a deploy issue for dev
        uses: ./.github/actions/create-deploy-issue
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ matrix.value }} 
          version: ${{ inputs.version }}
          env: dev
