name: CI

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'projects to deploy'
        required: true
      version:
        description: 'version to deploy'
        required: true

jobs:  
  parse:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - id: set-matrix
        run: |
          npm install @actions/core
          node -e 'const core=require("@actions/core"); const projects=("${{ github.event.inputs.projects }}").split(","); core.setOutput("matrix", JSON.stringify(projects))'

  create:
    needs: parse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.parse.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'hello youtube' > output.txt

      - name: Create a deploy issue for dev
        uses: ./.github/actions/create-deploy-issue
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubRunNumber: ${{ github.run_number }}
          project: ${{ matrix.value }} 
          version: ${{ github.event.inputs.version }}
          environment: dev
