
name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '/deploy') }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
      project: ${{ fromJSON(steps.issue_body_parser.outputs.payload).project }}
      version: ${{ fromJSON(steps.issue_body_parser.outputs.payload).version }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload_marker: target_payload 
  
  deploy-dev:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToDev') 
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: dev
    steps:
      - uses: actions/checkout@v2
                         
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          issueNumber: ${{ github.event.issue.number }}  
          project: ${{ needs.parse.outputs.project }} 
          version: ${{ needs.parse.outputs.version }}
          environment: ${{ env.DEPLOY_ENV }}
    
  deploy-test:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToTest') 
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: test
    steps:
      - uses: actions/checkout@v2
                         
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          issueNumber: ${{ github.event.issue.number }}  
          project: ${{ needs.parse.outputs.project }} 
          version: ${{ needs.parse.outputs.version }}
          environment: ${{ env.DEPLOY_ENV }}

  deploy-prod:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToProd') 
    runs-on: ubuntu-latest    
    env:
      DEPLOY_ENV: prod
    steps:
      - uses: actions/checkout@v2
              
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          issueNumber: ${{ github.event.issue.number }}  
          project: ${{ needs.parse.outputs.project }} 
          version: ${{ needs.parse.outputs.version }}
          environment: ${{ env.DEPLOY_ENV }}
          deployCommand: ${{ github.event.comment.body }}
    
    
    
    
    
