
name: Deploy

on:
  issue_comment:
    types: [created]

jobs:  
  parse:
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == 'Approved' }}
    runs-on: ubuntu-latest
    outputs:
      deploy-environment: ${{ fromJSON(steps.issue_body_parser.outputs.payload).environment }}
      ci-run-number: ${{ fromJSON(steps.issue_body_parser.outputs.payload).runNumber }}
      projects: ${{ fromJSON(steps.issue_body_parser.outputs.payload).projects }}
      version: ${{ fromJSON(steps.issue_body_parser.outputs.payload).version }}
    steps:
      - name: Comment on Issue      
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: 'Deployment Initiated 🚀'
          
      - name: Get Issue Data
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}         
          payload_marker: target_payload 
  
  deploy-dev:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToDev') 
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: dev
    steps:
      - uses: actions/checkout@v2
                         
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          projects: ${{ needs.parse.outputs.projects }} 
          version: ${{ needs.parse.outputs.version }}
          env: ${{ env.DEPLOY_ENV }}
          
      - uses: JasonEtco/create-an-issue@v2
        name: Create approval Issue for test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: test
          RUN_NUMBER: ${{ needs.parse.outputs.ci-run-number }}
          PROJECTS: ${{ needs.parse.outputs.projects }}
          VERSION: ${{ needs.parse.outputs.version }}
        with:
          filename: .github/issues/deployment-approval.md
    
  deploy-test:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToTest') 
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: test
    steps:
      - uses: actions/checkout@v2
                         
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          projects: ${{ needs.parse.outputs.projects }} 
          version: ${{ needs.parse.outputs.version }}
          env: ${{ env.DEPLOY_ENV }}

      - uses: JasonEtco/create-an-issue@v2
        name: Create approval Issue for prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: prod
          RUN_NUMBER: ${{ needs.parse.outputs.ci-run-number }}
          PROJECTS: ${{ needs.parse.outputs.projects }}
          VERSION: ${{ needs.parse.outputs.version }}
        with:
          filename: .github/issues/deployment-approval.md

  deploy-prod:
    needs: [parse]
    if: contains(github.event.comment.body, '/deployToProd') 
    runs-on: ubuntu-latest    
    env:
      DEPLOY_ENV: prod
    steps:
              
      - name: Deploy to ${{ env.DEPLOY_ENV }}
        uses: ./.github/actions/deploy
        with: 
          projects: ${{ needs.parse.outputs.projects }} 
          version: ${{ needs.parse.outputs.version }}
          env: ${{ env.DEPLOY_ENV }}
    
    
    
    
    
